export const GET_RECOMMENDED_MOVIE = "GET_RECOMMENDED_MOVIE";
export const GET_RECOMMENDED_MOVIE_SUCCESS = "GET_RECOMMENDED_MOVIE_SUCCESS";
export const GET_RECOMMENDED_MOVIE_ERROR = "GET_RECOMMENDED_MOVIE_ERROR";
